FROM python:3.11-slim

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir \
torch --index-url https://download.pytorch.org/whl/cpu

COPY inference_server ./inference_server
COPY shared ./shared

WORKDIR /code/inference_server

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
